#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jsmin
Version  : 2.2.2
Release  : 9
URL      : https://files.pythonhosted.org/packages/17/73/615d1267a82ed26cd7c124108c3c61169d8e40c36d393883eaee3a561852/jsmin-2.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/17/73/615d1267a82ed26cd7c124108c3c61169d8e40c36d393883eaee3a561852/jsmin-2.2.2.tar.gz
Summary  : JavaScript minifier.
Group    : Development/Tools
License  : MIT
Requires: jsmin-license = %{version}-%{release}
Requires: jsmin-python = %{version}-%{release}
Requires: jsmin-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
jsmin
        =====
        
        JavaScript minifier.
        
        Usage
        =====

%package license
Summary: license components for the jsmin package.
Group: Default

%description license
license components for the jsmin package.


%package python
Summary: python components for the jsmin package.
Group: Default
Requires: jsmin-python3 = %{version}-%{release}

%description python
python components for the jsmin package.


%package python3
Summary: python3 components for the jsmin package.
Group: Default
Requires: python3-core
Provides: pypi(jsmin)

%description python3
python3 components for the jsmin package.


%prep
%setup -q -n jsmin-2.2.2
cd %{_builddir}/jsmin-2.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588710036
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jsmin
cp %{_builddir}/jsmin-2.2.2/LICENSE.txt %{buildroot}/usr/share/package-licenses/jsmin/2f94c4708104fd49d7ced250326cf8878c1ae07e
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jsmin/2f94c4708104fd49d7ced250326cf8878c1ae07e

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
